#
# $Source: /home/reuter/archive/project/ImageSound/IS/src/examples/Makefile.rca $
# $Revision: 1.1 $
# $Aliases: beta2 $
# $Author: reuter $
# $Date: Sat Jun 27 14:59:58 1998 $
# $State: Experimental $
#

all:
	cd MIDI2PNM ; make all
	cd gif ; make all
	cd 1848 ; make all
	cd cd-cover ; make all

clean:
	cd MIDI2PNM ; make clean
	cd gif ; make clean
	cd 1848 ; make clean
	cd cd-cover ; make clean

veryclean:
	cd MIDI2PNM ; make veryclean
	cd gif ; make veryclean
	cd 1848 ; make veryclean
	cd cd-cover ; make veryclean
